repos:
  # GDScript Toolkit
  - repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: 4.5.0
    hooks:
      - id: gdlint
        name: gdlint
        description: "gdlint - linter for GDScript"
        entry: gdlint
        language: python
        language_version: python3
        require_serial: true
        types: [gdscript]
        exclude: ^addons/
      - id: gdformat
        name: gdformat
        description: "gdformat - formatter for GDScript"
        entry: gdformat
        language: python
        language_version: python3
        require_serial: true
        types: [gdscript]
        exclude: ^addons/
  - repo: local
    hooks:
      - id: godot-type-check
        name: Godot Type Check
        entry: bash -c '${GODOT_BIN:-/usr/local/bin/godot} --headless --quit --editor --path .'
        language: system
        pass_filenames: false
        files: \.(gd|tscn|tres)$
