repos:
  # GDScript Toolkit
  - repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: 4.5.0
    hooks:
      - id: gdlint
        name: gdlint
        description: "gdlint - linter for GDScript"
        entry: gdlint
        language: python
        language_version: python3
        require_serial: true
        types: [gdscript]
        exclude: ^addons/
        stages: [pre-commit, pre-push]
      - id: gdformat
        name: gdformat
        description: "gdformat - formatter for GDScript"
        entry: gdformat
        language: python
        language_version: python3
        require_serial: true
        types: [gdscript]
        exclude: ^addons/
        stages: [pre-commit, pre-push]
  # Type checking with Godot
  - repo: local
    hooks:
      - id: godot-type-check
        name: Godot Type Check
        description: "Type check GDScript files using Godot editor"
        entry: ./scripts/type_check.sh
        language: system
        pass_filenames: false
        stages: [pre-push]
