name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

# We can't set environment variables in copilot-setup-steps.yml at all so inling instead...
# env:
#   GODOT_VERSION: "4.5.1"
#   GODOT_BIN: /usr/local/bin/godot
#   GDUNIT4_VERSION: "6.0.1"

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install Python dependencies
        run: pip3 install -r requirements.txt

      - name: Install pre-commit hooks
        run: pre-commit install

      - name: Setup Godot
        uses: ./.github/actions/setup-godot
        with:
          godot-version: "4.5.1"
          godot-bin: /usr/local/bin/godot

      - name: Download and Install GdUnit4
        run: |
          mkdir -p addons
          cd addons
          wget -q "https://github.com/MikeSchulze/gdUnit4/archive/refs/tags/v6.0.1.zip"
          unzip -q "v6.0.1.zip"
          mv "gdUnit4-6.0.1/addons/gdUnit4" .
          rm -rf "gdUnit4-6.0.1" "v6.0.1.zip"

      - name: Verify Setup
        run: |
          echo "Godot installed:"
          ls -la /usr/local/bin/godot
          echo "Godot version:"
          /usr/local/bin/godot --version --headless
          echo "GdUnit4 installed:"
          ls -la addons/gdUnit4/plugin.cfg
