name: "Copilot Setup Steps"

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install GDScript Toolkit and pre-commit
        run: pip3 install "gdtoolkit>=4.0,<5.0" pre-commit

      - name: Install pre-commit hooks
        run: pre-commit install
      
      - name: Download and Install Godot 4.5.1
        run: |
          cd /tmp
          wget -q https://github.com/godotengine/godot/releases/download/4.5.1-stable/Godot_v4.5.1-stable_linux.x86_64.zip
          unzip -q Godot_v4.5.1-stable_linux.x86_64.zip
          chmod +x Godot_v4.5.1-stable_linux.x86_64
          echo "GODOT_BIN=/tmp/Godot_v4.5.1-stable_linux.x86_64" >> $GITHUB_ENV
      
      - name: Download and Install GdUnit4 v6.0.1
        run: |
          mkdir -p addons
          cd addons
          wget -q https://github.com/MikeSchulze/gdUnit4/archive/refs/tags/v6.0.1.zip
          unzip -q v6.0.1.zip
          mv gdUnit4-6.0.1/addons/gdUnit4 .
          rm -rf gdUnit4-6.0.1 v6.0.1.zip
      
      - name: Enable GdUnit4 Plugin in project.godot
        run: |
          if ! grep -q "\[editor_plugins\]" project.godot; then
            echo "" >> project.godot
            echo "[editor_plugins]" >> project.godot
            echo "" >> project.godot
            echo 'enabled=PackedStringArray("res://addons/gdUnit4/plugin.cfg")' >> project.godot
          fi
      
      - name: Verify Setup
        run: |
          echo "Godot version:"
          $GODOT_BIN --version --headless
          echo "GdUnit4 installed:"
          ls -la addons/gdUnit4/plugin.cfg
