name: GDScript Static Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  static-checks:
    name: 'Static checks'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v5
    - uses: Scony/godot-gdscript-toolkit@master
    - run: gdformat --check scripts/
    - run: gdlint scripts/

  unit-tests:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    needs: static-checks
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true
    - name: GdUnit4 - Test Runner Action
      uses: MikeSchulze/gdUnit4-action@v1.2.2
      with:
        godot-version: '4.5.0'
        paths: |
          res://test/
        timeout: 5
        report-name: test_report.xml
