name: GDScript Static Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  static-checks:
    name: 'Static checks'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v5
    - uses: Scony/godot-gdscript-toolkit@master
    - run: gdformat --check scripts/
    - run: gdlint scripts/

  type-check:
    name: 'Type Check'
    runs-on: ubuntu-latest
    needs: static-checks
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true
    - name: Download Godot
      run: |
        wget -q --show-progress https://github.com/godotengine/godot/releases/download/4.5.1-stable/Godot_v4.5.1-stable_linux.x86_64.zip
        # Verify checksum for security
        echo "73f7edcbb23ffe8b1c05e2ba60cf86f026b4e0452fa3e84f19d8c23e27788f65  Godot_v4.5.1-stable_linux.x86_64.zip" | sha256sum -c -
        unzip -q Godot_v4.5.1-stable_linux.x86_64.zip
        chmod +x Godot_v4.5.1-stable_linux.x86_64
    - name: Type Check Scripts
      run: |
        ./Godot_v4.5.1-stable_linux.x86_64 --headless --quit --editor --path .

  unit-tests:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    needs: type-check
    permissions:
      contents: read
      checks: write
    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true
    - name: GdUnit4 - Test Runner Action
      uses: MikeSchulze/gdUnit4-action@v1.2.2
      with:
        godot-version: '4.5.1'
        paths: |
          res://test/
        timeout: 5
        report-name: test_report.xml
